name = "FiberNlse"
uuid = "21c1a3e3-8543-4069-a1c4-5ed3e2bf6e2f"
authors = ["curio-sitas <paradisepx@gmail.com>"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "~1.7.2"
FFTW = "~1.3.2"
Plots = "~1.21.0"