name = "FiberNlse"
uuid = "21c1a3e3-8543-4069-a1c4-5ed3e2bf6e2f"
authors = ["curio-sitas <paradisepx@gmail.com>"]
version = "1.0.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"

[compat]
FFTW = "~1.3.2"
ProgressBars = "~1.4.0"
julia = "~1.7"
